const DeviceSensorsConfig = {
  "Chamber 1": [
    {
      title: "Oxygen Volume",
      xLabel: "Time",
      yLabel: "L",
      min: 150,
      max: 300,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 24,
      autoUpdates: true,
    },
    {
      title: "Hydrogen Volume",
      xLabel: "Time",
      yLabel: "L",
      min: 300,
      max: 500,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 24,
      autoUpdates: true,
    },
    {
      title: "Pressure",
      xLabel: "",
      yLabel: "PSI",
      min: 14,
      max: 16,
      decimal: 1,
      intervalType: "minute",
      intervalValue: 1,
      initialValues: 1,
      autoUpdates: true,
    },
    {
      title: "Energy Consumption",
      xLabel: "Time",
      yLabel: "kW",
      min: 0.01,
      max: 0.02,
      decimal: 2,
      intervalType: "hour",
      intervalValue: 1,
      initialValues: 18,
      autoUpdates: true,
    },
    {
      title: "Water Level",
      xLabel: "Water Reservoir",
      yLabel: "%",
      min: 30,
      max: 90,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },
    {
      title: "Temperature",
      xLabel: "Time",
      yLabel: "°C",
      min: 60,
      max: 70,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },

  ],

  "Chamber 2": [
    {
      title: "Oxygen Volume",
      xLabel: "Time",
      yLabel: "L",
      min: 150,
      max: 300,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 24,
      autoUpdates: true,
    },
    {
      title: "Hydrogen Volume",
      xLabel: "Time",
      yLabel: "L",
      min: 300,
      max: 500,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 24,
      autoUpdates: true,
    },
    {
      title: "Pressure",
      xLabel: "",
      yLabel: "PSI",
      min: 14,
      max: 16,
      decimal: 1,
      intervalType: "minute",
      intervalValue: 1,
      initialValues: 1,
      autoUpdates: true,
    },
    {
      title: "Energy Consumption",
      xLabel: "Time",
      yLabel: "kW",
      min: 0.01,
      max: 0.02,
      decimal: 2,
      intervalType: "hour",
      intervalValue: 1,
      initialValues: 18,
      autoUpdates: true,
    },
    {
      title: "Water Level",
      xLabel: "Water Reservoir",
      yLabel: "%",
      min: 30,
      max: 90,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },
    {
      title: "Temperature",
      xLabel: "Time",
      yLabel: "°C",
      min: 60,
      max: 70,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },

  ],
  "Chamber 3": [
    {
      title: "Oxygen Volume",
      xLabel: "Time",
      yLabel: "L",
      min: 150,
      max: 300,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 24,
      autoUpdates: true,
    },
    {
      title: "Hydrogen Volume",
      xLabel: "Time",
      yLabel: "L",
      min: 300,
      max: 500,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 24,
      autoUpdates: true,
    },
    {
      title: "Pressure",
      xLabel: "",
      yLabel: "PSI",
      min: 14,
      max: 16,
      decimal: 1,
      intervalType: "minute",
      intervalValue: 1,
      initialValues: 1,
      autoUpdates: true,
    },
    {
      title: "Energy Consumption",
      xLabel: "Time",
      yLabel: "kW",
      min: 0.01,
      max: 0.02,
      decimal: 2,
      intervalType: "hour",
      intervalValue: 1,
      initialValues: 18,
      autoUpdates: true,
    },
    {
      title: "Water Level",
      xLabel: "Water Reservoir",
      yLabel: "%",
      min: 30,
      max: 90,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },
    {
      title: "Temperature",
      xLabel: "Time",
      yLabel: "°C",
      min: 60,
      max: 70,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },

  ],
  "Water Reservoir" : [
    {
      title: "Water Level",
      xLabel: "Water Reservoir",
      yLabel: "%",
      min: 30,
      max: 100,
      decimal: 0,
      intervalType: "minute",
      intervalValue: 30,
      initialValues: 1,
      autoUpdates: true,
    },
  ],
};

module.exports = {DeviceSensorsConfig};

